# DOCKER ENV

export SIGNATURE_SERVICE_NAME="be-signature"
export SIGNATURE_SERVICE_IMAGE_NAME="signature-service"
export SIGNATURE_SERVICE_IMAGE_VERSION="0.0.1"
export NETWORK_NAME="bridge-signature"

# DOCKER IMAGE UPDATE

if docker image inspect $SIGNATURE_SERVICE_IMAGE_NAME:$SIGNATURE_SERVICE_IMAGE_VERSION &> /dev/null; then
    docker image rm -f $SIGNATURE_SERVICE_IMAGE_NAME:$SIGNATURE_SERVICE_IMAGE_VERSION
fi

docker build -t $SIGNATURE_SERVICE_IMAGE_NAME:$SIGNATURE_SERVICE_IMAGE_VERSION .

# DOCKER SERVICE RUN

if [ "$(docker ps -aq -f name=$SIGNATURE_SERVICE_NAME)" ]; then
    docker rm -f $SIGNATURE_SERVICE_NAME
fi

docker run -d \
--network $NETWORK_NAME \
--name $SIGNATURE_SERVICE_NAME \
-p $SIGNATURE_SERVICE_PORT:$SIGNATURE_SERVICE_PORT \
$SIGNATURE_SERVICE_IMAGE_NAME:$SIGNATURE_SERVICE_IMAGE_VERSION